### ISSUE TITLE
Request for Update for Rasa v2.4.x

### ISSUE THREAD

**Issue by xi1570-krupeshanadkat** [RasaHQ/wellness-check-bot#2]
Hey,
I am trying to learn rasa forms. and wherever I go I see outdated code and I can't follow along. So far I tried Udemy Rasa for Beginners course, then I tried blog article https://blog.rasa.com/how-to-build-your-first-rasa-form/ everywhere I see outdated code that no longer works for rasa v2.4.x

Please update the codebase, it would be huge help!

**Comment by kmanadkat** [comment]
I have submitted [pull request](https://github.com/RasaHQ/wellness-check-bot/pull/3) for review, that addresses above issue. I sat for like more than 10 hours starting from absolute scratch, finally it worked and I learnt basics of rasa :)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
Thanks for bringing this up!

@rgstephens Could you please have a look?

**Comment by kmanadkat** [comment]
I think this issue can be now close #3 has addressed it :)
